// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvfvgXbmaQkV7JLR8WHNGOZX2BlY5oko',
    appId: '1:174596478041:web:ce42fcf89fad896231cd48',
    messagingSenderId: '174596478041',
    projectId: 'furnigo-e74ea',
    authDomain: 'furnigo-e74ea.firebaseapp.com',
    storageBucket: 'furnigo-e74ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuQAxXsS5TcSHH11BfNxIyBDmC7EDDGRA',
    appId: '1:174596478041:android:cf651aa71832e49931cd48',
    messagingSenderId: '174596478041',
    projectId: 'furnigo-e74ea',
    storageBucket: 'furnigo-e74ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSXwe1PczavlSH2o9yVix2uPC75ub6HfU',
    appId: '1:174596478041:ios:fbd7e3d72c5b242731cd48',
    messagingSenderId: '174596478041',
    projectId: 'furnigo-e74ea',
    storageBucket: 'furnigo-e74ea.appspot.com',
    iosBundleId: 'com.example.furnigo',
  );
}
